### ISSUE TITLE
Consider adding an automation adapter

### ISSUE THREAD

**Issue by regevbr** [yeoman/environment#102]
I have created an automation adapter [yeoman-automation-adapter](https://github.com/regevbr/yeoman-automation-adapter) 
Yeoman automation adapter is used for creating automatic responses to user prompts. Used when creating automations to run yeoman without user interaction.

I think that it (or a variation of it) should come built in with the module and we need to document that addition.

@SBoudrias what do you think?

**Comment by regevbr** [comment]
It is different in the way it provides you with a ability to see the log output for debugging purposes and doesn't silently hide diff issues (future feature). It also doesn't use sinon stubs which are bot necessary on production code. Also the fact that it is not used for testing makes it eligible for a different location then yo-test which would allow automation creators to import it easily

**Comment by regevbr** [comment]
Maybe we should make the test adapter utilize my adapter to fit for testing to avoid code reuse

**Comment by SBoudrias** [comment]
If we can get close features parity, I'd by happy to see these two Adapters come together as one.

**Comment by regevbr** [comment]
Sounds good. Maybe i can create an abstract adapter and pass factories to create the log methods and the test adapter can use locally the sinon stubs and the automation adapter will use the real logger. @SBoudrias should i continue with a pr for this?

**Comment by SBoudrias** [comment]
This sounds good, PR is welcomed.

I'm not sure an extra adapter should be added to yeoman-environment though. I still feel like it'd be more appropriate in `yeoman-test`, but we could also just create another package if necessary.

**Comment by regevbr** [comment]
I will do the pr, but I don't see why not add it to the environment package? It is the package used for automations and that is where it will be needed...

**Comment by SBoudrias** [comment]
From my point of view mainly because it's not a super common use case for most users of this package. I want to make sure we keep the package lean so it doesn't incur extra dependencies cost.

If it's lean and don't require to add extra dependencies, it'd be okay with me.
