### ISSUE TITLE
If generator is loaded as an object, resolved and namespace values are dropped

### ISSUE THREAD

**Issue by esheffield** [yeoman/environment#107]
I'm developing a generator using Typescript. I've found that when the generator is instantiated the `resolved` and `namespace` properties are lost and default to `unknown` and `*` respectively.

Doing some experimenting with `environment.js` I found that when calling my generator the `Generator` variable has this structure:
```
{
  resolved: "..."
  namespace: "..."
  default: function() // my class constructor
}
```
compared to other generators I examined where `Generator` loads as a function (the class constructor) with the `resolved` and `namespace` as properties of the function.

There's a check for this at [environment.js#L378](https://github.com/yeoman/environment/blob/master/lib/environment.js#L378), but it then calls 'this.instantiate' only passing the constructor. Therefore the other properties are lost.

**Comment by SBoudrias** [comment]
Sounds like something we might've forgot. Do you want to send a PR fixing this? Sounds like you found all the relevant code pieces

**Comment by esheffield** [comment]
Sure, I experimented a bit with a local patch that seems to take care of. I'll clean that up and should be able to have something in a day or two.

**Comment by mshima** [comment]
Looks like this is fixed.
