### ISSUE TITLE
Running local generators by paths

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/environment#11]
We should support running a generators that are part of a project.

I see two solutions:

1. Allow paths as generator name (e.g.: `yo ./generators/generator-local`)
2. Add a standard local directory to the generators lookup (like always lookup for `$PWD/yeoman` - or similar)

Adding a lookup should be easy enough. Running via paths could be more difficult as that would probably require to change the way alias/namespace is working.

**Comment by enumag** [comment]
:+1: Please add this feature. Yeoman is useless for me without it.

**Comment by vanthoom** [comment]
+1

**Comment by marcusvetter** [comment]
+1

**Comment by w1res** [comment]
+1 I would love to have something like this. It would be very helpful for setting up internal generators company wide. That way non-technical people could just type `yo` and browse the list of available projects/files they can make.

**Comment by aaronpowell** [comment]
Pondering this issue and a quick dig in the code my assumption is that you would need to update this method - https://github.com/yeoman/environment/blob/master/lib/resolver.js#L109 or change https://github.com/yeoman/environment/blob/master/lib/resolver.js#L34 to call another method to find non-npm generators.

So this leads to the next question, how would the path(s) be configured? It could be convention based, say a `generators` folder relative to `yo` being called so if the you did `yo my-local-generator` it first looks in the `node_modules` paths and then `generators`.

Another idea would be to add something to the `.yo-rc.json` file, either a property at the root (`paths: []`) or a property of the generator in the file:

    {
        "my-local-generator": { "$$path": "./generators/my-local-generator" }
    }

The problem with that is finding something unique enough that you won't clash with the current usage.

Anyone have any other thoughts?

**Comment by cancerberoSgx** [comment]
+1 this is mandatory in my case since I'm writing automated tests on my development environment and I can't 'sudo npm link' there to install the generator that I want to test (and I don't want to). Please add it.

**Comment by SBoudrias** [comment]
`npm update -g yo` to pull the latest version and runs generators by path :)

**Comment by aiswebmaster** [comment]
Is there an example of how you would run a local generator by path with the latest version of yo?

**Comment by SBoudrias** [comment]
@aiswebmaster `yo ./path/to/a/generator-name/app/index.js`

**Comment by mixn** [comment]
Just wanted to say “thank you” for this. :)

**Comment by mixn** [comment]
As a quick follow-up question, how would I list all local generators, is there a way to accomplish this?

`yo --generators` seemingly lists all, instead, I’d prefer to just list the ones that are in `generators/` so that internal devs know which things exist and can be called through `yo ./generators/component-name/index.js`.

Thanks!

**Comment by SBoudrias** [comment]
@mixn the idea behind running them by path is that we cannot know a generator exists there. So I don't think this would be possible.

Although, provided they're all in the same folder, you can run `ls ./my-generator-folder`
