### ISSUE TITLE
Considering adding a "dry run" option

### ISSUE THREAD

**Issue by daaren-urthling** [yeoman/environment#110]
It would be useful to have an option that allow to do almost everything but not committing the FS in the end (similar to --dry-run for Angular CLI).
This may allow to review the list of files added, changed and the eventual conflicts.
As far as the MemFS is used, it should be relative simple to skip the last "commit" phase.
Maybe this is already possible by tweaking in some way the generator ...

**Comment by daaren-urthling** [comment]
Ok, I'll give it a try. I am not exactly a guru in node.js development, so I'll take my time ;o)
I am currently working (as a side project) on a generator for a legacy framework of my organization and to fulfill some needs I need to get more and more involved in the yeoman internals, so maybe I will be able to sort it out.
In case of need for some hint, what's the best option? Should I fork the repo and invite you, or add some issue here?

**Comment by SBoudrias** [comment]
@daaren-urthling you can ping me on our gitter channel; and maybe some other people can also jump in to give you a hand.

**Comment by daaren-urthling** [comment]
Perfect! Let's do this way, thanks a lot.

**Comment by anupbaranwal** [comment]
Hey did you try this? I need this feature in my application. I would like to give it a try if I get a bit help. :)

**Comment by daaren-urthling** [comment]
No, I didn't progress with this project, I had other priorities

**Comment by shousper** [comment]
I was also after this because it's a little faster than writing tests while prototyping generators. I ended up creating a "BaseGenerator" to extend that overrides `spawnCommand` and `fs`.

In the constructor I added this:

```javascript
    // Hi-jack fs module to add dry run and verbose support.
    this.fs = new Proxy(this.fs, {
      get: (target, propKey) => {
        if (typeof target[propKey] !== 'function' || propKey.startsWith('exists') || propKey.startsWith('read')) {
          return target[propKey];
        }
        // eslint-disable-next-line consistent-return
        return (...fnArgs) => {
          if (this._dryRun) {
            this.log(this._verbose
              ? `${propKey} ${JSON.stringify(fnArgs, null, 2)}`
              : `${propKey}(${fnArgs.join('", "')})`);
          } else if (this._verbose) {
            this.log(`${propKey}(${fnArgs.join('", "')})`);
          }
          if (!this._dryRun) {
            return target[propKey](...fnArgs);
          }
        };
      },
    });
```

And replacing `spawnCommand` was pretty simple:

```javascript
  // Override to implement dry-run and verbose modes.
  spawnCommand(command, args) {
    if (this._dryRun) {
      this.log(this._verbose
        ? `${command} ${JSON.stringify(args, null, 2)}`
        : `${command}(${args.join('", "')})`);
    } else if (this._verbose) {
      this.log(`${command}(${args.join('", "')})`);
    }
    if (!this._dryRun) {
      const { error } = super.spawnCommandSync(command, args);
      if (error) throw error;
    }
  }
```

Please forgive the dirty logging, etc.

Hope this helps someone 🙂
