### ISSUE TITLE
Support a configurable custom folder for generators lookup

### ISSUE THREAD

**Issue by bd82** [yeoman/environment#111]
Hello.

## Feature Request
Could it be possible to support a custom folder (e.g via an env variable)
for additional generators lookup?

This would be similar to using node.js [***NODE_PATH***](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders) env variable
except:
- it would only affect yeoman lookup instead of the whole node.js modules lookup.
- It would be a suffix to the lookup, rather than a prefix, so it would have low priority and won't override any other search results

## Context
The scenario is "pre-loading" yeoman generators in a **managed** environment 
that may also have nvm installed (**multiple** global node_modules directories).

## Discussion
- Is this a feature the environment module should support?
- Would a PR implementing this feature be favorably considered for merging?
- Is there another way to support the scenario described above?

Cheers.

**Comment by SBoudrias** [comment]
Hey, could you explain more about why the current default search paths do not work for you?

I'd be open to merging a PR for this, but first I'd want to make sure we really need to expand our API surface and that there's no way to fix your core issues automatically.

**Comment by bd82** [comment]
> Hey, could you explain more about why the current default search paths do not work for you?

Sure 😄 

I would like to provide a docker image that has a set of Yeoman generators **pre-installed.**
I could naturally install all of those generators globally, however I also intend that image to contain
[**nvm**](https://github.com/creationix/nvm) and with nvm each node version has it's **own** globals
so switching node version would cause those generators o disappear.

nvm has mitigation options for those globals scenarios:
- https://github.com/creationix/nvm#migrating-global-packages-while-installing
- https://github.com/creationix/nvm#default-global-packages-from-file-while-installing

However:
-  The first (migration argument) would require the end user to be aware that an additional argument needs to be passed each time.

- The second (listing default global packages) would cause many packages to be **re-installed**
   each time nvm is used to install a new versions.
   Also it would be difficult to manage & modify that set of global generators if it is duplicated
   for each node version.

So now we come to the [NODE_PATH](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders) argument
which by agumenting the node search path would allow me to create a pesudo super global directory
for yeoman generators.

Except that I am worried it may have unintended side effects:
- I don't want to effect node.js module resolution, Just Yeoman package lookup.
- The NODE_PATH is **prefixed** to the search path so it seems like it could take precedence
  over other results.

I just want to tell Yeoman: ***"Look at folder X for additional generators, but at a **low priority**"***
so the results from that folder would never override the default behavior, just add to it.

Do you have any  thoughts on how I could accomplish this other than via implementing this new feature in Yeoman-Env module?

Cheers. 😄

**Comment by SBoudrias** [comment]
You could install the generators in a folder one level higher than your workspace. Or you can put the generators directly in your project and run them with their paths.

If no workaround is satisfying for you, feel free to send a PR. I'll help review and merge.

**Comment by bd82** [comment]
> You could install the generators in a folder one level higher than your workspace

Thanks I will see if that suggestion could solve the problem first.

**Comment by bd82** [comment]
Closing this, will re-open if the top level folder won't be sufficient.

Thanks 👍
