### ISSUE TITLE
Implement advanced namespace specification

### ISSUE THREAD

**Issue by mshima** [yeoman/environment#139]
Make namespace strict with format (https://github.com/yeoman/environment/pull/136):
- should start with a valid node package name without `generator-`
- then generator path with `:` separator (more then one is allowed)
- then semver version for auto-install `()` separator (optional)
- then unique instance id with `+` separator (more then one is allowed)
- at last, flags:
  - optional flag ?: Don’t throw exception if not found.
  - load flag !: try to look for it if not registered.
  - install flag !!: try to install it automatically if not found.

Others:
- register generator instance with unique id, so it can be fetched later. (https://github.com/yeoman/environment/pull/131)
- ~~Add 2 more phases to environment: integration and transforming.~~ should be implemented at generator level (https://github.com/yeoman/generator/pull/1150)

**Comment by SBoudrias** [comment]
How about installing the packages automatically if not found?

**Comment by mshima** [comment]
@SBoudrias can you take a look at https://github.com/yeoman/environment/pull/136.
It’s already big, I want to merge it before moving forward.
It’s missing the force flag and instance registering.
