### ISSUE TITLE
Environment 2.8.0

### ISSUE THREAD

**Issue by mshima** [yeoman/environment#142]
@SBoudrias can you release 2.8.0?

Merged:
- All commits that were just exposing lookup options. (Shouldn't have behavior change)
- Fixed a precedence bug (https://github.com/yeoman/environment/commit/9465e8a0496d9b0432afaba309899e73177c4b3f)
- Fixed lookupGenerator with package namespace bug (https://github.com/yeoman/environment/commit/79703f9be1ed094c238cb9a993748aaf8f782b6f)
- Implemented isPackageRegistered (https://github.com/yeoman/environment/commit/e80219818524afcc8f9f5afa4f37ddf934bf5c12)

- Shared data between generators (https://github.com/yeoman/environment/pull/155)
- Catch generator's instantiation errors (https://github.com/yeoman/environment/pull/151)
- Add windows to CI (https://github.com/yeoman/environment/pull/149)

- Change lookup to return structure with package details (https://github.com/yeoman/environment/pull/146)

Thanks.

**Comment by SBoudrias** [comment]
@mshima with your approval, I'll release 2.8.0

**Comment by mshima** [comment]
Yes you can release.

**Comment by mshima** [comment]
@SBoudrias it will be great if you release generator 4.6.0 as it is in master now too.
I need to get the instance of composeWith for one task I am work on and that's not possible without https://github.com/yeoman/generator/commit/aebe760a43898566f7810c2bcb3c14c2cba51ed5

**Comment by SBoudrias** [comment]
it's out!
