### ISSUE TITLE
Environment.getGeneratorNames()

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/environment#19]
We currently have `Environment.getGeneratorsMeta()`, but it returns more than we usually need and we need to manually format the output. Would be nice to have a simple method to just get the generator names as an array.

Currently I have this hack in place that I would like to remove: https://github.com/yeoman/yo/blob/681bf11ee5619fd76a093abb04a660784a835d96/lib/utils/index.js#L8-L10

**Comment by arthurvr** [comment]
Once the `Environment.namespaceToName` PR landed I'll do this one.

**Comment by sindresorhus** [comment]
Was landed: https://github.com/yeoman/environment/commit/db159ff9e28151c9c81e9c198df862ab8fb27a5f

**Comment by arthurvr** [comment]
Yuuuppp, thanks for the reminder! Was just going through these issues so will do this one today or tomorrow (:

**Comment by sindresorhus** [comment]
ping :)
