### ISSUE TITLE
Node is required & empty .yo-repository folder being created 

### ISSUE THREAD

**Issue by AnanyaJha** [yeoman/environment#227]
We use yeoman to scaffold new projects and recently we've noticed that yeoman requires node to be installed for the end user and creates an empty `.yo-repository` folder in the directory that the command is being run from. It looks like this change was introduced around two months ago with release 2.9.0 and I wanted to understand whether this was intended. Is it necessary to have node involved and is this folder supposed to be used for something, and if not, is there a way to remove the need for node & the generation of this folder?

**Comment by mshima** [comment]
It’s fixed in #228
