### ISSUE TITLE
existing and new generator now claims to be "not installed" when it IS installed

### ISSUE THREAD

**Issue by ksnyde** [yeoman/environment#234]
I have a generator that i've used for years and a new one that's close to "out of the box" and they both are experiencing a mind-boggling error. I've created a video of this problem here:

[https://www.screencast.com/t/2aY1Npmu](video)

In a nutshell, both of my generators can be installed with `npm i -g generator-my-generator` and when I just run `yo` they show up as options, they can also be updated via yo's interactive menu, but when I go to run them they say that the Generator is not installed!

In my most recent case -- regarding the repo `generator-lambda-typescript` the exact message it says is:

> You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/. 
Install them with npm install generator-lambda-typescript:app.

This suggestion of installing via `npm install generator-lambda-typescript:app` is clearly a syntax error as the `:app` will not be recognized by NPM. Instead it seems to appear to be a reference to the "default generator" name ... which is defined in the repo.

Where the transpiled version of `index.js` is as follows:
[CODE](https://github.com/inocan-group/generator-lambda-typescript/blob/59d3e142882c090132040a820ef9496d5aee68c9/generators/app/index.js)

I used Rollup (and the typescript plugin to rollup) to transpile but I also tried with transpiling with just Typescripts `tsc` and that behaved the same.

**Comment by mshima** [comment]
A exception should be thrown at:
https://github.com/yeoman/environment/blob/0bd0b956010a971671adda8dc247bc81d96894d2/lib/environment.js#L582
When `typeof Generator !== 'function'`

**Comment by ksnyde** [comment]
Ok, this is helpful and reassuring to have a baseline to aim at. Now I need to understand why Typescript and Rollup transpilations have changed and how to ensure they get back to this contract.

**Comment by ksnyde** [comment]
It would seem that you used to be able define a named export like so:

```typescript
import Base from "yeoman-generator";
export class Generator extends Base {
  constructor(args: any[], opts: any) {
    super(args, opts);
  }
}
```

and this would be usable but now you're required to export a default:

```typescript
export { Generator as default } from "./Generator"
```

Not sure when this happened or whether it qualifies as a breaking change in semver but it feels like it probably should. Certainly broke my generator :)

**Comment by ksnyde** [comment]
As I looked for an answer it may be that at some point I changed my `tsconfig.json` settings to include the `allowSynethicDefaultImports` which can be helpful a lot of times but in this case definitely was _not_ helpful. My generator now looks like this:

```typescript
import * as YeomanGenerator from "yeoman-generator";
import * as chalk from "chalk";

import { computerText, install } from "./private";

export class Generator extends YeomanGenerator {
  constructor(args: any[], opts: any) {
    super(args, opts);
  }

  initializing() {
    console.log(computerText);
    console.log(chalk`\nStarting the {green Lambda Typescript} generator. {italic For AWS functions with attitude!}\n`);
  }

  install() {
    install(this);
  }
}
```

and my `tsconfig.json` like this:

```typescript
export { Generator as default } from "./Generator";
```

Is there anywhere in the docs that some baseline config would be helpful?

**Comment by mshima** [comment]
> Not sure when this happened or whether it qualifies as a breaking change in semver but it feels like it probably should. Certainly broke my generator :)

I don't think yeoman is to blame about this, looks like yeoman-environment didn't supported `exports.Generator` at 2.0.0.

> Is there anywhere in the docs that some baseline config would be helpful?

I don't think we have TS example at our docs, a full TS example would be helpful.
