### ISSUE TITLE
Extracting resolver.getNpmPaths() to a separate node module

### ISSUE THREAD

**Issue by jviotti** [yeoman/environment#24]
In a project that I'm working on, I'm implementing plugin support using the approach that Yeoman uses:
- Scan all npm paths for a matching pattern (like `generator-` but related to my project).
- Require them accordingly.

I found `yeoman-environment`'s `getNpmPaths()` while attempting to write a similar function. In order to reuse this code, I'm requiring the whole `yeoman-environment`, but I feel this function could be a candidate for a separate module, as other people might be trying to resolve this issue as well, and they could rely on the experimentation you put in when implementing that function.

What do you think about extracting this function as a separate node module (maybe something like `npm-path-find`)?

**Comment by sindresorhus** [comment]
:+1: I've been thinking the same. Just forgot to open an issue. Definitely needs to be done.

**Comment by jviotti** [comment]
If it's feasible, it might also worth to extract `findGeneratorsIn()` (https://github.com/yeoman/environment/blob/master/lib/resolver.js#L63) in a generic way that allows people to search for installed packages matching a pattern.

**Comment by sindresorhus** [comment]
I'm :+1: for extracting anything that can be reused outside of the environment module.

**Comment by SBoudrias** [comment]
We need to be careful about how much we extract and how much we divide.

The resolver is a very performance sensible part of Yeoman, and breaking it in multiple sub-module will make it hard to refactor/improve the performance.

If we extract, we need to be careful keeping thing consistent and making sure we can make improvement to the flow without needing to coordinate multiple modules updates.

**Comment by sindresorhus** [comment]
@SBoudrias Sure, but aren't they already focused and independent functions? Why will it make it hard?

**Comment by supergray** [comment]
> @SBoudrias Sure, but aren't they already focused and independent functions? Why will it make it hard?

> I would actually argue the opposite. Right now it's hidden here. If more people could use it they might contribute perf improvements, since they depend on it.

+100000 :+1:
