### ISSUE TITLE
`npm audit` reports severe vulnerability for dependency of `yeoman-environment:^2.10.3`.

### ISSUE THREAD

**Issue by cgranade** [yeoman/environment#247]
When taking a dependency on `yeoman-environment:^2.10.3`, `npm audit` reports a high-security vulnerability from the dependency path `yeoman-environment` → `npm-api` → `paged-request` → `axios`. The root cause for this report is https://github.com/axios/axios/pull/3410, with a corresponding issue on `paged-request` at https://github.com/jonschlinkert/paged-request/pull/3.

```
$ npm audit
...

  High            Server-Side Request Forgery                                   

  Package         axios                                                         

  Patched in      >=0.21.1                                                      

  Dependency of   yeoman-environment                                            

  Path            yeoman-environment > npm-api > paged-request > axios          

  More info       https://npmjs.com/advisories/1594

...
```

**Comment by mshima** [comment]
Duplicate of https://github.com/yeoman/environment/issues/246

**Comment by cgranade** [comment]
Apologies for the duplicate, I got a GitHub error posting #246 and did not realize the issue was created successfully.
