### ISSUE TITLE
globby is out of date on yeoman-environment

### ISSUE THREAD

**Issue by pjmattingly** [yeoman/environment#248]
When installing yeoman, I get the warning:

> warning yo > yeoman-environment > globby > fast-glob > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

I traced the issue to the version of globby used (=> Found "globby@9.2.0"), where the latest version of globby is 11.0.2 (At time of writing; see: https://www.npmjs.com/package/globby).

Cheers.

**Comment by mshima** [comment]
globby@10 had a node version bump, so it cannot be updated in environment@2.x.
Current master have it updated.
