### ISSUE TITLE
[Feature Request] dependency on package manager (npm, yarn, etc.)

### ISSUE THREAD

**Issue by hatpick** [yeoman/environment#272]
I see that in ```package-manager.js``` that one can provide which package manager to be used via options.
It means that the users need to have a package manager installed on their machine. 
What if I want to bundle a package manager such as [npm](https://www.npmjs.com/package/npm) with the code and want it to be used by this library (to remove the users' need to have them installed on their machine)? 

is there a way I can pass the path to my custom package manager via options to be used?

**Comment by mshima** [comment]
yeoman-environment@3.2.0/yeoman-generator@5.2.0 supports customInstallTask feature.
