### ISSUE TITLE
outdated types in @types/yeoman-environment

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [yeoman/environment#273]
The latest release of the @types/yeoman-environment package is 2.10.2

I know the major was just bumped a week ago, but any chance we can get the typings updated soon?

**Comment by a-b-r-o-w-n** [comment]
Commenting to remove stale label. This is still needed.

**Comment by manuth** [comment]
@a-b-r-o-w-n is there something specific missing in `@types/yeoman-environment`?

**Comment by cgranade** [comment]
It looks like `Environment.run` is still listed as taking a callback parameter in `@types/yeoman-environment@v2.2.3`, but it was changed to an async method in `yeoman-environment@3.4.1` such that the TypeScript compiler complains when `await`ing the result of `.run`.

**Comment by GerbenRampaart** [comment]
Yes I'm running into this as well. I thought I was overlooking something.

**Comment by tdashworth** [comment]
I'm not even sure which version it's based on, maybe v2.x.x. 

If I get the time, I'll try to contribute back some updated types although the docs site isn't terribly informative, especially around the `TerminalAdapter` - a key extension point.

**Comment by tburny** [comment]
I also ran into this and got quite frustrated. Writing Yeoman generators is already a bit difficult, but writing a custom cli Frontend for a set of generators is nearly impossible if Your Typescript compiler tells you there are issues that practically only exist in the type definition files, but not in the code of itself.

Still thanks a lot for developing and maintaining Yeoman, it seems to be one of the only reasonable tools on the market (besides degit, which has a different approach).

**Comment by manuth** [comment]
I finally found some time to refactor the type declarations of `yeoman-environment`.
I opened up a new PR just a few seconds ago. Stay tuned.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58614

**Comment by tdashworth** [comment]
That's amazing! Thank you @manuth, I'll take a look now.

**Comment by mshima** [comment]
yeoman-enviroment has built-in types now.
