### ISSUE TITLE
Remove start/end events

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/environment#28]
re https://github.com/yeoman/environment/issues/5#issuecomment-70714778

**Comment by twixie** [comment]
Can I submit a PR for this?

**Comment by sindresorhus** [comment]
Sure :)

**Comment by SamVerschueren** [comment]
Is this only issue only about removing the [`end`](https://github.com/yeoman/environment/blob/master/lib/environment.js#L75) and [`initializing`](https://github.com/yeoman/environment/blob/master/lib/environment.js#L68) lines? (and [here](https://github.com/yeoman/environment/blob/master/lib/environment.js#L453-L462) as well off course). Or should `initializing` be kept?

// @SBoudrias

**Comment by SBoudrias** [comment]
@SamVerschueren every events related to running generators.
