### ISSUE TITLE
addDevDependencies/addDependencies should respect .npmrc

### ISSUE THREAD

**Issue by yanni4night** [yeoman/environment#308]
I have a .npmrc in cwd，and  a *registry* defined in it, but yeoman still trys fetching from npmjs.org, which responses 404.

**Comment by mshima** [comment]
Seems related to https://github.com/yeoman/environment/issues/307 to me.
npm is executed using spawnCommand and cwd is missing.

**Comment by baconandon** [comment]
FWIW I traced this back to the [`resolvePackage` function in `composability.js`](https://github.com/yeoman/environment/blob/main/lib/composability.js#L67)

So it looks like this is a shortcoming of `pacote` - see e.g. https://github.com/npm/pacote/issues/77

**Comment by baconandon** [comment]
@mshima based on what I found (pacote issue?) I'm not sure that this is related to #307
> Seems related to #307 to me.

**Comment by mshima** [comment]
I got it, if this is related to addDependencies and addDevDependencies methods, this should be discussed in https://github.com/yeoman/generator/issues/1304.
