### ISSUE TITLE
Yeoman-Environment doesn't detect `package.json`-changes properly

### ISSUE THREAD

**Issue by manuth** [yeoman/environment#309]
When changing the `destinationRoot` of the generator (which I do whenever running a yeoman-generator), features such as detecting `package.json`-changes:
https://github.com/yeoman/environment/blob/0b2b99a9bce3bf852e710dda86b94fa8b54942d0/lib/package-manager.js#L12-L14
Detecting the preferred package-manager:
https://github.com/yeoman/environment/blob/0b2b99a9bce3bf852e710dda86b94fa8b54942d0/lib/package-manager.js#L31-L37
Don't work correctly (while `yeoman-generator`s `packageJson` feature works as expected).

This issue is caused by the environment's `this.cwd` not matching the generator's `destinationRoot`.

**Comment by mshima** [comment]
yeoman-generator@4 changes environment `this.cwd` to the generator destinationRoot at constructor.
Not every composed generator needs to have the same `destinationRoot`, composing another generator with another `destinationRoot` would change the environment `this.cwd` and can break the original generator behavior.

yeoman-generator@5 doesn't change environment `this.cwd` because of this problem.
You need to change the environment cwd manually.

**Comment by manuth** [comment]
Is it planned to change something about the `package-manager`-extension or the `Environment.cwd`-behavior in order to make it work without having to change `Environment.cwd` manually?

Something like a separate field (such as `Environment.contextDir`) for storing the current generator's `destinationRoot`?

**Comment by mshima** [comment]
It's possible to create `forwardToEnv` parameter at generator's `destinationRoot` method.
It's not possible to create current generator's behavior.

**Comment by jgoblwr** [comment]
@manuth @mshima when you are saying "change the environment cwd manually" where and how exactly would you do that? In the generator somewhere?

**Comment by manuth** [comment]
Set the environment's `cwd`-field (`this.env.cwd = [...]`) and optionally change the current working-directory by invoking `process.chdir(...)`.

I used this workaround in one of my projects:
https://github.com/manuth/ExtendedYoGenerator/blob/8e9ff185f71151a87db23af8bb54b7cea1d69c3f/packages/extended-yo-generator/src/Generator.ts#L214-L234

**Comment by jgoblwr** [comment]
> Set the environment's `cwd`-field (`this.env.cwd = [...]`) and optionally change the current working-directory by invoking `process.chdir(...)`.
> 
> I used this workaround in one of my projects:
> https://github.com/manuth/ExtendedYoGenerator/blob/8e9ff185f71151a87db23af8bb54b7cea1d69c3f/packages/extended-yo-generator/src/Generator.ts#L214-L234

@manuth great thanks for that. I didn't realise `this.env` was available 🤦‍♂️ inside generator class

**Comment by manuth** [comment]
No worries - glad I could help 😄
