### ISSUE TITLE
Capturing console output in generator

### ISSUE THREAD

**Issue by barrettc** [yeoman/environment#323]
I've written a custom generator that I'm integrating in another tool. I'm wondering if there's an easy way to construct my Yeoman environment to pass in my logger or somehow capture the output of my generator. For example, I'd like to be able to do something like:

```
const env = yeoman.createEnv()
env.register(require.resolve('generator-whatever'))
const results = await env.run('whatever')
```

And then have the output of the generator in my `results` instead of the results going to console.log. Thanks for any help!

**Comment by mshima** [comment]
You should take a look at adapter parameter passed to the environment, there is a console inside.
