### ISSUE TITLE
Vulnerability around ansi-regex

### ISSUE THREAD

**Issue by gee4vee** [yeoman/environment#372]
https://security.snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908

Similar issue happening in other components. It appears npm-log is one source of vulnerability.
https://github.com/mapbox/node-pre-gyp/issues/620

Dep tree for 3.8.0:

```
└─┬ yeoman-environment@3.8.0
  └─┬ @npmcli/arborist@4.0.4
    └─┬ @npmcli/run-script@2.0.0
      └─┬ node-gyp@8.4.0
        └─┬ npmlog@4.1.2
          └─┬ gauge@2.7.4
            └─┬ strip-ansi@3.0.1
              └── ansi-regex@2.1.1
```

**Comment by symphony-youness** [comment]
This issue is fixed in npmlog@6.0.0
