### ISSUE TITLE
Improve #lookup() test performance

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/environment#4]
The #lookup() test install generators for real and is taking quite a while to run. We could probably speed this test a lot by stopping using npm and mocking the full environment to run the test in.

**Comment by Freyert** [comment]
Here are some thoughts I had on this subject.

A. Installing JQuery isn't really necessary and could be done with a simple dummy-generator.
B. Perhaps add a postinstall hook to npm to setup the dummy project.

How's that sound?

**Comment by SBoudrias** [comment]
There's an issue with that. A post install hook means the test itself don't control the environment it's running in, as so it'll be eventually flakey.

And installing a simpler generator still mean we'll do multiple networks request to complete the installation.

So the goal is should be:

1. The test need to setup its own context to ensure it'll pass
2. No network request (so we shouldn't install using NPM)

So, this being said, how should we manage this?

Well, I see two potential solutions:

1. Manually copy-paste fake generators in the global node_modules
2. `npm link` test generators
