### ISSUE TITLE
Cannot import YeomanCommand

### ISSUE THREAD

**Issue by frbuceta** [yeoman/environment#406]
Imported YeomanGenerator with require:
```js
const {YeomanCommand} = require("yeoman-environment/lib/util/command");
```

And, when executing, it tells me this
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/command' is not defined by "exports" in /home/fran/Projects/create-loopback/node_modules/yeoman-environment/package.json
```

**Comment by frbuceta** [comment]
There is no tutorial on how to make a CLI with yeoman-environment?

**Comment by mshima** [comment]
Something like
```
await Environment.prepareCommand(require('./generators/custom-generator'))(process.argv); 
```
https://github.com/yeoman/environment/blob/60945ed387ae56b86570d5f295ab9e0c4fade30f/test/command.js#L139-L140

**Comment by frbuceta** [comment]
> Something like
> 
> ```
> await Environment.prepareCommand(require('./generators/custom-generator'))(process.argv); 
> ```
> 
> https://github.com/yeoman/environment/blob/60945ed387ae56b86570d5f295ab9e0c4fade30f/test/command.js#L139-L140

It works, thanks for the help. There is not much information about this
