### ISSUE TITLE
bundling and `PACKAGE_NAME_PATTERN` in resolver.js

### ISSUE THREAD

**Issue by bd82** [yeoman/environment#417]
Hello.

I am trying to bundle our Yeoman generators and wish to avoid using any `externals` due to performance considerations.
- These generators are installed **on startup** in a container based dev env for customers...

I have a small issue with this line:
- https://github.com/yeoman/environment/blob/cb46b68ece80e26ecd0f43ce5e28bf758b3fa88e/lib/resolver.js#L14-L16

Which I believe I can easily resolve by replacing it with:
- `PACKAGE_NAME_PATTERN = "yeoman-environment";`

I am just wondering:
- Is this workaround safe?
- Why is "yeoman-environment" part of the patterns? 
   - is it loaded like other generators? is this a special case?
   - I see elsewhere in the code referring to `generator-*` in the patterns which makes more sense to me.

Thanks.

**Comment by mshima** [comment]
Indeed `PACKAGE_NAME_PATTERN` looks wrong

**Comment by bd82** [comment]
Thanks for the info
