### ISSUE TITLE
`env.instantiate` options seem to be broken ('skip-install')

### ISSUE THREAD

**Issue by moritzraho** [yeoman/environment#421]
## What does not work anymore

I used to instantiate and run a generators like follows:

```
 const env = yeoman.createEnv()
 const appGen = env.instantiate(myRequiredGenerator, { options: { 'skip-install': true } })
 await env.runGenerator(appGen)
```

This used to work but now does not skip install anymore. I couldn't pinpoint the exact time this started to fail.

## Work-around

const env = yeoman.createEnv()
env.options = { skipInstall: true }
 const appGen = env.instantiate(myRequiredGenerator)
 await env.runGenerator(appGen)

**Comment by mshima** [comment]
Install is done by the environment since last major version of environment/generator.
```
const env = yeoman.createEnv(undefined, { skipInstall: true })
const appGen = env.instantiate(myRequiredGenerator)
await env.runGenerator(appGen)
```

**Comment by moritzraho** [comment]
Thanks for the details @mshima
