### ISSUE TITLE
Method getNpmPaths of resolver.js  doesn't contain OS X default nodejs path

### ISSUE THREAD

**Issue by anstarovoyt** [yeoman/environment#43]
Here https://github.com/yeoman/environment/blob/master/lib/resolver.js#L140 you add default the linux path but default OS X path is '/usr/local/lib/node_modules/'.
So if I try to run non-globally installed yo it cannot find generators.

**Comment by SBoudrias** [comment]
Something else is probably wrong then, because these paths are really a safety fallback.

Either way, PR welcomed to add `/usr/local/lib/node_modules/` in there.

**Comment by anstarovoyt** [comment]
@SBoudrias thanks
