### ISSUE TITLE
Can you please follow semver?

### ISSUE THREAD

**Issue by twixie** [yeoman/environment#45]
Hello,
Dear Yeoman maintainers,

A while ago I submitted a PR (landed in https://github.com/yeoman/environment/commit/72c91a8f8920aabaccb8bdcd70f4eb5d10922f10) which implemented a new method. A while ago I woke up and noticed that there was a release: `1.2.7`. That's a patch version bump. Really cool, thanks for the quick release, though, why a patch version bump?

So I have a question: does the yeoman team follow semver? If not, is there a possibility to do so, please? If you don't want to use semver (which is the default convention on npm), I think you will have to warn for that in the documentation.

I see many people using the `^` when it comes to deps developed by the yeoman team. That would then be invalid as npm assumes semver by default.
 
Thanks in advance.
东 栋

**Comment by sindresorhus** [comment]
I agree, it should have been a `minor` release. We follow semver on all Yeoman projects. This was just an oversight our part.

// @SBoudrias

**Comment by arthurvr** [comment]
Ha! Told ya before... https://github.com/yeoman/generator-node/commit/e3b9534d4e45f68be875fd2d220b715197510397 ;)


This was just a tiny mistake but we can't really fix this anymore, so I'm going to close this issue. Let's try to do a better job at following semver in the future. @twixie Sorry for the confusion.

**Comment by twixie** [comment]
> Let's try to do a better job at following semver in the future. 

@SBoudrias @arthurvr @sindresorhus :+1: Glad to hear that.
