### ISSUE TITLE
with yeoman-enviroment 3.18.1, getting error `generatorArgs` of undefined

### ISSUE THREAD

**Issue by amitkc1** [yeoman/environment#476]
Hello,

After the recent release of yeoman-environment, we're getting the following error. 

`Cannot read property 'generatorArgs' of undefined
2023/05/18 18:01:56  exit status 1
`
We suspect that this is related to the recent release of yeoman-environment because there is a change related to `generatorArgs`.

**Comment by mshima** [comment]
`3.18.2` released with a guessed fix.
A stack trace would be nice.

**Comment by mshima** [comment]
I suppose it's fixed. Closing.
