### ISSUE TITLE
@yeoman-environment@3.19.3 has deprecated NPM module "@npmcli/arborist@4.3.1"

### ISSUE THREAD

**Issue by stein2nd** [yeoman/environment#484]
**Describe the bug**

npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs

npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

npm WARN deprecated debuglog@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

The following is the result of executing "npm ls readdir-scoped-modules":
![](https://user-images.githubusercontent.com/531628/258131595-24de3a6e-6df2-4b39-a5da-5ff6b0d7bbf4.png)

The following is the result of executing "npm ls @npmcli/move-file":
![](https://user-images.githubusercontent.com/531628/258136226-8c665564-89ca-4750-8d71-440a79cc59db.png)

The following is the result of executing "npm ls debuglog":
![](https://user-images.githubusercontent.com/531628/258135360-d9e54118-7a75-416a-95e1-b542611c872e.png)

If "yeoman-environment" updates its own "@npmcli/arborist" to 6.3.0 or higher, I think these bugs will be resolved.

**What is the current behavior?**

**To Reproduce**

**Expected behavior**

**Screenshots**

## System:
 - OS: macOS 13.5
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 285.12 MB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 20.5.0 - ~/.nodebrew/current/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 9.8.0 - ~/.nodebrew/current/bin/npm

**Additional context**

**Comment by mshima** [comment]
Those are transitive dependencies, can be fixed by recreating package-lock.json.
`rm -rf package-lock.json node_modules && npm install`
