### ISSUE TITLE
some NPM modules are outdated.

### ISSUE THREAD

**Issue by stein2nd** [yeoman/environment#485]
After cloning to a local drive, I ran "ncu -u" and it indicated that some NPM modules were outdated:

> Upgrading [User home directory]/Documents/GitHub/environment/package.json
> [====================] 41/41 100%
>  @types/lodash-es             ^4.17.7  →  ^4.17.8
>  @yeoman/adapter               ^1.1.0  →   ^1.2.0
>  @yeoman/conflicter            ^1.0.7  →   ^1.0.8
>  c8                            ^8.0.0  →   ^8.0.1
>  chalk                         ^5.2.0  →   ^5.3.0
>  execa                         ^7.1.1  →   ^7.2.0
>  fly-import                    ^0.3.0  →   ^0.3.1
>  globby                       ^13.1.4  →  ^13.2.2
>  mem-fs-editor                ^10.0.1  →  ^10.0.2
>  prettier                      ^2.8.8  →   ^3.0.1
>  prettier-plugin-packagejson   ^2.4.3  →   ^2.4.5
>  rimraf                        ^5.0.0  →   ^5.0.1
>  semver                        ^7.5.0  →   ^7.5.4
>  sinon                        ^15.0.4  →  ^15.2.0
>  slash                         ^5.0.1  →   ^5.1.0
>  strip-ansi                    ^7.0.1  →   ^7.1.0
>  typescript                    ^5.0.4  →   ^5.1.6
>  xo                            0.54.2  →   0.55.0

I ran "npm install" and it indicated that some depricated:
> npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

![image](https://github.com/yeoman/environment/assets/531628/d9f495a4-fbbe-4a0e-9a15-04c3d1e10f8f)
...Maybe that fixing "fly-import" to call the latest version of "@npmcli/arborist" will eliminate this warning.

I ran "npm audit fix" and it indicated below:
> # npm audit report
> 
> nth-check  <2.0.1
> Severity: high
> Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
> No fix available
> node_modules/nth-check
>   css-select  <=3.1.0
>   Depends on vulnerable versions of nth-check
>   node_modules/css-select
>     cheerio  0.19.0 - 1.0.0-rc.3
>     Depends on vulnerable versions of css-select
>     node_modules/cheerio
>       tui-jsdoc-template  *
>       Depends on vulnerable versions of cheerio
>       node_modules/tui-jsdoc-template
> 
> 4 high severity vulnerabilities

## System:
 - OS: macOS 13.5
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 285.12 MB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 20.5.0 - ~/.nodebrew/current/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 9.8.0 - ~/.nodebrew/current/bin/npm

**Comment by mshima** [comment]
Those are transitive dependencies, can be fixed by recreating package-lock.json.
`rm -rf package-lock.json node_modules && npm install`
