### ISSUE TITLE
Can't discover generators compiled with Babel6

### ISSUE THREAD

**Issue by soulwu** [yeoman/environment#49]
I really like ES6 and build a generator using ES6 syntax in source. 
I use Babel to transpile source to ES5. 
Since Babel upgrade to 6.0 and [**Kill CommonJS default export behaviour**](https://github.com/babel/babel/issues/2212)
```js
export default MyGenerator;
```
will be transformed to:
```js
exports.default = MyGenerator;
```
and `module.exports = exports["default"]` will no longer exist

yeoman-environment can't discover my generator for me.

Consider add support to `require('generator-xxx').default` for all generators compiled with Babel?

**Comment by SBoudrias** [comment]
Not sure what is Node.js take on es6 modules.

Yeoman is a Node.js tools, so I believe we'll be following the standard of the platform.

**Comment by sindresorhus** [comment]
We're not going to add Babel specific semantics to our code. It's up to you to make something CommonJS compatible.

You can add this in your code as a workaround:

```
module.exports = require('./transpiled/index').default;
```

I'm sure someone will create a Babel plugin for this.
