### ISSUE TITLE
Issue with v4 with local namespaces

### ISSUE THREAD

**Issue by nvuillam** [yeoman/environment#497]
I'm trying to upgrade in v4 because v3.x.x crashes when called from a JS module

But now I see the following error

```
For help, see: https://nodejs.org/en/docs/inspector
file:///C:/git/megalinter/mega-linter-runner/node_modules/yeoman-environment/dist/environment-base.js:205
                throw new TypeError(chalk.red(`You don't seem to have a generator with the name “${namespace?.generatorHint}” installed.`) +   
                      ^

TypeError: You don't seem to have a generator with the name “undefined” installed.
```

Here is how yeoman-environment is called

![image](https://github.com/yeoman/environment/assets/17500430/47d4b832-a320-4de4-909d-38adf00c4263)

Do you have any tip ? :)

**Comment by strmer15** [comment]
@mshima Can this be reopened? It looks like a problem with the parser in `@yeoman/namespace` not allowing local paths. I've opened https://github.com/yeoman/yeoman-api/issues/5 for that, but this package would need to be updated with any new version.

**Comment by mshima** [comment]
Local paths should be converted to a valid namespace here:
https://github.com/yeoman/environment/blob/f1bfab377a53615a7e004603e0f57c1b16d0533d/src/environment-base.ts#L272-L274

**Comment by strmer15** [comment]
Ah, ok - thanks for that info! Looks like it's throwing an error because the `resolvedOrigin` in the `resolveModulePath` function is `undefined`. If I comment out the `else` block in that function it seems to work correctly again for local paths.

Should I create a PR to remove that (or adjust that logic)? Or are you already working on a fix?

**Comment by mshima** [comment]
Please go ahead.

**Comment by strmer15** [comment]
> Please go ahead.

Thanks! I've created https://github.com/yeoman/environment/pull/504 to address it, let me know if that seems good.

**Comment by mshima** [comment]
The sample usage is wrong, the bug is not valid. Should be:
```
await env.run([generatorPath]);
```

@strmer15 your usage looks related to relative paths.
Please post your use case in a new issue.
