### ISSUE TITLE
Simplify API

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/environment#5]
Just some thoughts and questions on things we can do to simplify the API. I'd be happy to open separate ticket for things, but want to hear them out first.

- Why does this module depend on `yeoman-generator`? And shouldn't the usage example be `var yeoman = require('yeoman-generator');` => `var env = require('yeoman-environment');`?

- I think we should drop `env.createEnv()` as you can already do `new Env()`? Which is IMHO better.

--

```js
// The #lookup() method will search the user computer for installed generators. The search
// if done from the current working directory.
env.lookup(function () {
  env.run('angular', { 'skip-install': true }, done);
});
```

Any reason we have to do the lookup first? Can't just `env.run` lazy trigger the lookup on the first run?

I would like to have a way to run a generator with a single method call.

--

The `end` event doesn't seem to work: https://github.com/yeoman/yo/blob/8f8d16e10c13d11faf7034ca2f1e59589a6081bd/cli.js#L78-L80 How is it different from the callback to `env.run`? Can we drop it?

--

Is the `help` method used at all https://github.com/yeoman/environment/blob/a03a150570ca8b9a8f9de13783d2d6dadf378f0c/lib/environment.js#L87 ?

--

`env.getGeneratorsMeta()` is weird as it only works after `env.lookup`. Could we instead pass generator metadata in the `env.lookup` callback?

--

I'm not a big fan of the aliasing functionality. It complicates things a lot. Is there a way we can drop or simplify this?

https://github.com/yeoman/yo/blob/8f8d16e10c13d11faf7034ca2f1e59589a6081bd/cli.js#L75-L76

--

Anything anyone else think can be improved?

**Comment by sindresorhus** [comment]
@SBoudrias :arrow_up:

**Comment by sindresorhus** [comment]
> I think you're correct. It's always been generators:end (or namespace:end) https://github.com/yeoman/environment/blob/master/test/environment.js#L482

done: https://github.com/yeoman/yo/commit/e40800c06b3ab665f55310d3bc9342715981b94b

> We can drop from yo side as we already set the default aliases on the environment: https://github.com/yeoman/environment/blob/8cf15b8e288707805af3cef57d7f62234c340180/lib/environment.js#L54

done: https://github.com/yeoman/yo/commit/6a603d90d9173eaca44e4aee381036960dd0d78b

> Is the :all alias used at all?

I've added a deprecated comment https://github.com/yeoman/yo/commit/6a603d90d9173eaca44e4aee381036960dd0d78b#diff-f8849ae9f0614ba9464fdd14c2d98dc0R71 Is there any way we can intercept that route and console.log a deprecation message?

**Comment by sindresorhus** [comment]
@SBoudrias :arrow_double_up:

**Comment by SBoudrias** [comment]
> >I feel a lot of use case for yeoman-environment are not related to running a generator. As so I believe a multi-step process make sense.
> Then can we introduce a meta method that does both?

Well, as yeoman-environment is not widely used a lot, I prefer to stick to the current way for the moment. The two step really make it clear to a consumer what is actually going on. The lookup method take a while to run while run is super fast to start. Also I feel most external use cases for yeoman-environment don't require the lookup phase.

> I've added a deprecated comment yeoman/yo@6a603d9#diff-f8849ae9f0614ba9464fdd14c2d98dc0R71 Is there any way we can intercept that route and console.log a deprecation message?

Actually, this never worked, so I removed it from yo.

About the events in the previous comment, this also been changed in yeoman-environment recently, I think now there's only start/end - and I feel like we should remove them all until there's an actual use case.

**Comment by sindresorhus** [comment]
> and I feel like we should remove them all until there's an actual use case.

Which events? `start`/`end`?

**Comment by SBoudrias** [comment]
@sindresorhus Yes, they don't make sense in the context of the environment as it is the runner. It can run multiple generators and can basically run forever.

The start/end, if listened to, should be listened to on a generator instance, not the environment.
