### ISSUE TITLE
Get arguments/options of sub-generator

### ISSUE THREAD

**Issue by SamVerschueren** [yeoman/environment#50]
Hi, I'm not sure if this is possible, so if not, just tell me and close the issue :).

So in a sub-generator, it's possible to define arguments and options as described in the section [Arguments](http://yeoman.io/authoring/user-interactions.html) (and Options). Is it possible to retrieve those together with the generators metadata?

The reason I'm asking this is because I'm writing a [VS Code plugin](https://github.com/SamVerschueren/vscode-yo) and I support sub-generators. But some sub-generators have arguments, which I'm not aware off. As you can see in [this](https://github.com/SamVerschueren/vscode-yo/blob/master/src/extension.ts#L40-L50) block off code, I'm running the sub-generator, if it throws an error with a specific message, I show an input box where the user can pass in it's argument. This feels very hacky and I was hoping for a better way.

The same goes for the options. If I could retrieve the options of a sub-generator, I can show a multi-select list where the user can pick the options he wants.

Any thoughts on this?

**Comment by SBoudrias** [comment]
I don't think we have it explicitly exposed. You can call `.help()` to get the help message.

We should totally fix this.
