### ISSUE TITLE
Remove Makefile

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/environment#51]
looks like make was used because gulp-mocha was broken. Should probably just run mocha directly no?

**Comment by SBoudrias** [comment]
We should just run `yo node` on the project.

**Comment by SBoudrias** [comment]
FWIW, gulp or gulp-mocha is still failing hard on asserting exceptions...

**Comment by SBoudrias** [comment]
I can drop the makefile, but we can't use gulp for now because gulp-mocha really is broken.
