### ISSUE TITLE
registerGeneratorsIn function

### ISSUE THREAD

**Issue by JSeed** [yeoman/environment#54]
Currently Environment provides the function findGeneratorsIn, which searches a list of paths and returns a list of generators within those paths.  From what I can tell, the user still has to loop through each found module, registering any generators found within.  If I am mistaken by all means correct me.

I would like to propose the addition of a registerGeneratorsIn method which receives a list of paths, uses the findGeneratorsIn function to find all the modules within these paths, and then registers all of the generators/sub-generators in the found modules.  Namespaces could be generated using the namespace method.  

If this addition makes sense I would be happy to start working on a PR.

**Comment by SBoudrias** [comment]
What's the use case?

**Comment by JSeed** [comment]
When registering a directory of custom generators to an environment.  In my case I have a bunch of project specific generators that I need to access.  Currently I am using findGeneratorsIn to find all of the modules and then looping through and registering all of the generators/sub generators within each module
