### ISSUE TITLE
getNpmPaths() prioritizing global modules over local modules

### ISSUE THREAD

**Issue by wwhurley** [yeoman/environment#57]
With the `paths.reverse()` call at https://github.com/yeoman/environment/blob/master/lib/resolver.js#L144 it causes the global paths to be returned first. Is that intended? It seems like we should go from the most specific -- the current project -- to the least specific -- the globally installed modules.

**Comment by SBoudrias** [comment]
@wwhurley did you encounter a bug?

We're matching the local folder first, the moving on to the globals ones.

**Comment by wwhurley** [comment]
Maybe. That paths that I'm getting from getNpmPaths() are:
```
\[ '/usr/lib/node_modules',
  '/opt',
  '/opt/local/lib/node_modules',
  '/Users/whurley/Sites/test/node_modules',
  '/Users/whurley/Sites/node_modules',
  '/Users/whurley/node_modules',
  '/Users/node_modules',
  '/node_modules' ]
```

This is causing yo to register the generator in my global node_modules directory and skip the one in ./node_modules. Looking the code that appears to be the intent of the code in getNpmPaths that adds the local paths, then the global paths and then reversing the array.

**Comment by SBoudrias** [comment]
> This is causing yo to register the generator in my global node_modules directory and skip the one in ./node_modules

You're 100% sure that's what's happening? We have unit test validating the opposite.

**Comment by wwhurley** [comment]
I'm seeing the results from findGeneratorsIn() return the generators in the correct order:
```
[ '/Users/whurley/Sites/test/node_modules/generator-web-starter',
  '/opt/local/lib/node_modules/generator-generator',
  '/opt/local/lib/node_modules/generator-web-starter' ]
```

However when I run `yo` and select my generator it's hitting the code that is in the global module. For instance in `/opt/local/lib/node_modules/generator-web-starter/app.index.js I have:

```
module.exports = generators.Base.extend({
  initializing : {
    plugins : function() {
      var env = this.env;
      console.log(env);process.exit();
      [...]
```

And then in `/Users/whurley/Sites/test/node_modules/generator-web-starter/app.index.js` I have:

```
module.exports = generators.Base.extend({
  initializing : {
    plugins : function() {
      var env = this.env;
      [...]
```

So when I run `yo` it hits the `console.log` statement and then dies.

**Comment by SBoudrias** [comment]
@wwhurley thanks for the details! I hope I didn't sound too dismissive, we just receive a ton of bug reports that are not backed by valid verification.

It looks to me like you've find the source of the bug, so feel free to send a PR!

This tests should've validated locally installed generator gets the priority https://github.com/yeoman/environment/blob/master/test/resolver.js#L74 - but it might be broken given what you described.

**Comment by wwhurley** [comment]
Changing that line resolves the issue in practice though it causes the unit tests to fail. I'll have to dig into the tests to see why that is.

**Comment by wwhurley** [comment]
I'm looking at some of the unit tests that were failing and I had some questions about them. Specifically:
* https://github.com/yeoman/environment/blob/master/test/resolver.js#L127
* https://github.com/yeoman/environment/blob/master/test/resolver.js#L144

Do you know what those are intending to test, @SBoudrias? Is the order in that array important or is it just inclusion in the array? Specifically, should I adjust the test to check the index in the array or could I just use `paths.find()`?

**Comment by SBoudrias** [comment]
@wwhurley The index matter (as you know), but it can be wrong currently.  So to fix them, it'd just change the index the reflect the correct position they should hold.
