### ISSUE TITLE
resolve.getNpmPaths - nvm prefix

### ISSUE THREAD

**Issue by mklabs** [yeoman/environment#59]
Might be related to #52 

---

I'm running into an issue when trying to load installed generators with `env#getGeneratorsMeta()`, and I think it's related to nvm and npm prefix being different than the defaults.

My test sample is something like: 

```js
var env = require('yeoman-environment').createEnv();
env.lookup((err) => {
  console.log(env.getGeneratorsMeta());
});
```

Looking at the `getNpmPaths()` method, I can see that `$NODE_PATH` is used when defined, and I can get the env lookup working with: 

    NODE_PATH="/home/user/.nvm/versions/nodes/v6.0.0/lib/node_modules" node test.js

My question is, would you agree on adding the result of `npm prefix` to the lookup paths automatically ?   

`env.lookup()` is asynchronous, so we might be able to introduce a call to `.exec('npm prefix -g')` if you don't mind the performance penalty it might introduce.

Alternatively, if you don't want it to be the default behavior, would it be possible to define custom paths? something like:

```js
// env.lookup([paths, ], cb);

env.lookup(['/home/user/.nvm/versions/node/v6.0.0/lib/node_modules'], function() {});
``` 

Either way, it would fix the lookup for nvm installed yeoman and generators. This doesn't apply when `yeoman-environment` is installed globally, `yo` works fine in this case.

**Comment by mklabs** [comment]
`$NVM_PATH` can also be used if defined in environment variables, might avoid spawning npm to run `npm prefix`

**Comment by SBoudrias** [comment]
Yeah, spawning a command is really, but reallllly SLOW. It's not a good option.

I'm okay with using `$NVM_PATH`

**Comment by mklabs** [comment]
Great! I'll probably send you a PR with this update.

**Comment by mklabs** [comment]
btw, really good job on extracting the environment in its own lib, very pleasant to work with and useful

**Comment by SBoudrias** [comment]
Thanks!

Also, FWIW, issues might arise more often now that npm behavior is to flatten dependencies. Right now we're always loading `{yeoman-environment root}/../../../..` as the global search path (yeoman-environment -> yo -> global root), but now that assumption might be wrong.

**Comment by mklabs** [comment]
yep, I had some issues with yo npm linked, but using the `NODE_PATH` trick I was able to work around.
