### ISSUE TITLE
Backwards incompatibility due to untildify requiring node4

### ISSUE THREAD

**Issue by TheSavior** [yeoman/environment#61]
I just re-installed one of my packages that depends on yeoman-test and have started getting an error because this package relies on @sindresorhus's https://github.com/sindresorhus/untildify version 3.0.1 which now requires node 4 and uses const. The semver tree has broken causing my once stable build to now fail.

I am currently using node 0.12.13 and my package has a dev dep on `"yeoman-test": "1.0.0"`

```
mygenerator/node_modules/yeoman-test/node_modules/yeoman-environment/node_modules/untildify/index.js:2
const osHomedir = require('os-homedir');
^^^^^
SyntaxError: Use of const in strict mode.
```

**Comment by matthewp** [comment]
I'm experiencing the same. I guess that the tests are not covering the use of untildify, because travis is still set up to test those environments.  Does yeoman-environment intend to continue to support them?

**Comment by matthewp** [comment]
I submitted a PR in #62 to downgrade the dependency.
