### ISSUE TITLE
1.6.2 deployed version is missing all source files

### ISSUE THREAD

**Issue by kageurufu** [yeoman/environment#67]
/tmp/ curl $(npm view yeoman-environment@1.6.2 dist.tarball) | tar -zt
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  1459  100  1459    0     0  10192      0 --:--:-- --:--:-- --:--:-- 10202
    package/package.json
    package/readme.md

Is this intentional? Its breaking react-native, as seen at https://github.com/facebook/react-native/issues/8610

**Comment by SBoudrias** [comment]
Obviously non-intentional.

That's a known npm bug. Will fix asap.

**Comment by SBoudrias** [comment]
Fixed with 1.6.3, also removed 1.6.2 from npm
