### ISSUE TITLE
Remove env#help() method

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/environment#7]
This help method is command line specific and should be removed from this module.

To do so, we'll need to reimplement this method inside [yo](https://github.com/yeoman/yo)

**Comment by supergray** [comment]
`easy` issues are open for longer then 2 years. Really not normal enymore.

**Comment by SBoudrias** [comment]
@supergray Deleted your comment, please review our [code of conduct](https://github.com/yeoman/yeoman/blob/master/code-of-conduct.md)

**Comment by supergray** [comment]
Deleting comments = not giving people a voice = against the code of conduct. That what I read.
