### ISSUE TITLE
Ability to use other require function in resolveModulePath

### ISSUE THREAD

**Issue by anta-semenov** [yeoman/environment#73]
I was trying to use yeoman-environment in project that was built with webpack and encountered a problem with generators registration.
Webpack replace original require function with it's own, so trying to require a generator absolute path caused an error 'Cannot find module'.
My proposal is to allow to user to pass it's own require function to createEnv method with options parameter and use this function in resolveModulePath.

If you think my proposal is good I would happy to make PR (Changes that I propose are follows: [https://github.com/anta-semenov/environment/commit/4505b7813913961cc2e151f7da82b98550d67440](url) )

**Comment by SBoudrias** [comment]
Generators are Node modules. Why would you ever want to use another module system?

**Comment by anta-semenov** [comment]
I don't want to use another module system.
Now I'm making package for atom editor and I'm use webpack for building. While building webpack replaces all 'require' statements with it's own implementation and this causes errors when I try to register generators with lookup function. So I don't need to change module system, but I need the way to provide original node 'require' function.

**Comment by sindresorhus** [comment]
This is not something the generator system should be concerned about. Instead, find a way to solve it with Webpack. Maybe with its `externals` config.
