### ISSUE TITLE
Cannot find module when using Environment.getByPath

### ISSUE THREAD

**Issue by duro** [yeoman/environment#74]
I am trying to embed my generator in my project using the `getByPath` method that was introduced here in PR #11 

My folder structure looks like this:

```
- /generators
--- /adrizer     <---- My embeded generator
------- /generators
---------- /app
------------- index.js
---------- /test
------------- index.js
------- package.json
```

I am trying to test running this generator using this command:

`./node_modules/.bin/yo ./generators/adrizer adrizer`

And I get this error:

```
module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/adamduro/Workspace/projects/adrizer-dashboard/generators/adrizer/'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at Environment.resolveModulePath (/Users/adamduro/Workspace/projects/adrizer-dashboard/node_modules/yeoman-environment/lib/environment.js:461:18)
    at Environment.register (/Users/adamduro/Workspace/projects/adrizer-dashboard/node_modules/yeoman-environment/lib/environment.js:161:25)
    at Environment.getByPath (/Users/adamduro/Workspace/projects/adrizer-dashboard/node_modules/yeoman-environment/lib/environment.js:276:10)
    at Environment.get (/Users/adamduro/Workspace/projects/adrizer-dashboard/node_modules/yeoman-environment/lib/environment.js:265:10)
    at Environment.create (/Users/adamduro/Workspace/projects/adrizer-dashboard/node_modules/yeoman-environment/lib/environment.js:296:24)
    at Environment.run (/Users/adamduro/Workspace/projects/adrizer-dashboard/node_modules/yeoman-environment/lib/environment.js:372:24)
    at /Users/adamduro/Workspace/projects/adrizer-dashboard/node_modules/yo/lib/cli.js:140:11
    at Array.forEach (native)
```

Any idea what I am doing wrong? Or was there a change to the way that `require.resolve` work in Node 6?

**Comment by SBoudrias** [comment]
`Cannot find module '/Users/adamduro/Workspace/projects/adrizer-dashboard/generators/adrizer/'`

Is there really a generator there? This is node.js module system not finding an index.js or package.json file in that directory.

Chances is you want `./node_modules/.bin/yo ./generators/adrizer/app/index.js adrizer` or something like that.

**Comment by duro** [comment]
@SBoudrias There definitely is a package.json in `./generators/adrizer`

Here it is:

```
{
  "name": "generator-adrizer",
  "version": "0.1.0",
  "description": "",
  "files": [
    "generators"
  ],
  "keywords": [
    "yeoman-generator"
  ],
  "dependencies": {
    "yeoman-generator": "^1.0.1"
  }
}
```

**Comment by duro** [comment]
@SBoudrias I even just tried recreating my generator using https://github.com/yeoman/generator-generator and I'm still getting this error.

**Comment by SBoudrias** [comment]
@duro can you print the tree of the folder?

**Comment by duro** [comment]
@SBoudrias Here you go:

```
├── README.md
├── generator-adrizer
│   ├── LICENSE
│   ├── README.md
│   ├── generators
│   │   └── app
│   │       ├── index.js
│   │       └── templates
│   │           └── dummyfile.txt
│   ├── gulpfile.js
│   ├── package.json
│   └── test
│       └── app.js
├── package.json
```

**Comment by SBoudrias** [comment]
@duro so as you see, there's no `index.js` files in the folder you pointed yo. So it cannot find the module you want to run.

You want to point yo to `generator-adrizer/generators/app/index.js` directly.

**Comment by duro** [comment]
@SBoudrias And that would apply to every sub-command as well?

**Comment by SBoudrias** [comment]
Yes exactly :)

**Comment by duro** [comment]
@SBoudrias So for local modules, I basically have to mimic the `name:sub-task` structure in my own main package.json for the project? I'm just trying to get a sense of best practice here.

**Comment by SBoudrias** [comment]
I don't really understand your question.

The only thing to know is that to run a generator with a path, you need to point to the generator `index.js` file directly, not a directory.

**Comment by duro** [comment]
Thanks!
