### ISSUE TITLE
Handle constructor parameters logic in the factory method.

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/environment#8]
The `Environment` constructor should be strict and allow only valid arguments (and throw otherwise).

The checks for partial signature or invalid inputs should be done in the factory function (`Environment.createEnv()`).

**Comment by twixie** [comment]
Can I submit a PR for this? I would like to.

**Comment by sindresorhus** [comment]
Go ahead :) Anything with the `actionable` label is pull requestsable.
