### ISSUE TITLE
Allow non-boolean parameters

### ISSUE THREAD

**Issue by eh-am** [yeoman/environment#80]
Right now we can only pass boolean params:

```
  env.run('angular', {'skip-install': true}, err => {
    console.log('done');
  });
```
(from the docs)

I'd like to pass Strings/Numbers, so that I can use it with [yeoman-option-or-prompt](https://github.com/artefact-group/yeoman-option-or-prompt)

**Comment by SBoudrias** [comment]
Did you try it? In theory, it should just work

**Comment by eh-am** [comment]
Ops, the issue is on their side. My bad.
