### ISSUE TITLE
Copy error when trying to run a generator in the same environment twice

### ISSUE THREAD

**Issue by mwebler** [yeoman/environment#82]
Hello there,

I'm not sure if this is supposed to work like this or if this is an error. But, when you call the same environment to run a generator again, it causes an assertion error for `copy` and `copyTpl` with glob patterns:

`AssertionError: Trying to copy from a source that does not exist: envir-test/node_modules/generator-generator/subgenerator/templates/templates/**`

Example :

```javascript
const yeoman = require('yeoman-environment');
const env = yeoman.createEnv();

env.lookup(() => {
  env.run('generator', {'skip-install': true}, err => {
    console.log('done');
    env.run('generator', {'skip-install': true}, err => {
        console.log('done');
    });
  });
});
```

Everything works fine if I create a new environment each time I execute the generator.

Versions:
- yeoman-environment: "^1.6.6"
- generator-generator: "^3.1.0",
- Node v7.10.0
- Windows 10

**Comment by SBoudrias** [comment]
Do you have the generator code?

**Comment by mwebler** [comment]
The error occurs using any generator which uses glob patterns in `copy` calls.

In the example above I'm running the [generator-generator](https://github.com/yeoman/generator-generator) v3.1.0.

**Comment by rgroothuijsen** [comment]
From what I can see by debugging the copy function, it adds files that were previously requested to an in-memory store, and somewhere along the way the globbed path is added to the list. On subsequent calls, it then mistakenly treats this as a literal path.
