### ISSUE TITLE
How is error handling supposed to work?

### ISSUE THREAD

**Issue by tyrsius** [yeoman/environment#89]
When running yeoman environment errors in generators get swallowed. I've trying using `env.on('error')` to register a handler, but it does not get invoked when a generator throws an error. The error param in the `run()` callback isn't set either. What's going on? How do we catch errors?

**Comment by SBoudrias** [comment]
Hey @tyrsius, it is very hard to see what is the issue you're running into. Usually errors aren't swallowed and exposed properly to the user; so you're definitely not hitting a normal behavior.

As such, I can't help you find the bug unless you provide a more complete example. Can you provide the exact code and steps to reproduce your issue?

**Comment by tyrsius** [comment]
@SBoudrias ☝️

**Comment by SBoudrias** [comment]
@tyrsius so if I understand this properly; only errors thrown inside _composed_ generators are not being catch?

**Comment by tyrsius** [comment]
Yes.

**Comment by SBoudrias** [comment]
Okay, this looks like a valid bug. I don't think I'll have much time to dig into it in the next week. But let me know if I can help you prepare a PR to fix that!

**Comment by SBoudrias** [comment]
@regevbr want to send a PR for this one? Looks like you got it figured out

**Comment by regevbr** [comment]
@sboudrias sure ill give it a go
