### ISSUE TITLE
Automatically build/release new API doc 

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/environment#9]
Each time we publish a new `tag`, we should launch a Travis-CI process to release a new version of the API documentation.

 A shareable solutions for a couple of our repositories would be very awesome. See:
- https://github.com/yeoman/generator/issues/673

**Comment by mischah** [comment]
I would like to take care of this 😗 

But before I just adapt the solution of yeoman/generator#971 I like to:

### 1. address this comment from @SBoudrias in yeoman/generator#968:  

> Right now it looks like it pushes for each travis run, it should probably only from a single process/node version.> Right now it looks like it pushes for each travis run, it should probably only from a single process/node version.

### 2. think about this comment from @SBoudrias in yeoman/generator#971

> It'd be even greater if we could somehow wrap this in a gulp plugin or just a command line tools to completely automate the process and make it easier to reuse between packages.

Ciao

**Comment by mischah** [comment]
> SBoudrias closed this in yeoman/generator#971 an hour ago

Oops. Why is this closed? Was it me? :dizzy_face:

**Comment by mischah** [comment]
Yep. It was me:

>  ![oops](https://cloud.githubusercontent.com/assets/441011/19549374/40bbbd28-96a4-11e6-8cd7-00b08d56c2ca.png)

Using a reserved over there. Sorry :pensive:

Could you reopen this one?
