### ISSUE TITLE
yarn linked generators cannot be found in Windows

### ISSUE THREAD

**Issue by gera2ld** [yeoman/environment#94]
Looking into the code, I found this:
```js
  // Yarn's file structure looks like this:
  //
  //   ~/.config/yarn/global/node_modules/yo/
  //   ~/.config/yarn/link/generator-i-made
```
But on Windows, the file structure looks like this:
```js
  //   %LOCALAPPDATA%\Yarn\config\global\node_modules\yo\
  //   %LOCALAPPDATA%\Yarn\config\link\generator-i-made
```

**Comment by uiii** [comment]
I'm looking now at yarn's directory structure and there is no `config` dir, but `Data` dir instead, so the path should be `%LOCALAPPDATA%\Yarn\Data\link\...` and `%LOCALAPPDATA%\Yarn\Data\global\...`

My yarn version is **1.6.0**

**Comment by gera2ld** [comment]
They have changed the paths several months ago:
https://github.com/yarnpkg/yarn/commit/2d454b552d447a0f79a04e4e451e926e1c0a29e7#diff-a7748843fbda5167d065231e3a2e7a1fR61

Perhaps we need an update.
