### ISSUE TITLE
Exception in resolver.findGeneratorsIn(...)

### ISSUE THREAD

**Issue by yannickadam** [yeoman/environment#97]
While running yo, the following error occurs: 
Error: EACCES: permission denied, scandir '/usr/sbin/authserver
(MacOS / High Sierra)

Culprit is here:
```javascript
  // Adds support for generator resolving when yeoman-generator has been linked
  if (process.argv[1]) {
        paths.push(path.join(path.dirname(process.argv[1]), '../..'));
  }
```
inside getNpmPaths(). My yo is at **/usr/local/bin/yo**, and this adds the whole **/usr** directory to the search path => globby.sync inside resolver.findsGeneratorIn will throw if some directories are not user readable.

Something like this fixes the issue:
```javascript
try {
      modules = modules.concat(globby.sync(
        ['generator-*', '@*/generator-*'],
        {cwd: root, onlyFiles: false, absolute: true}
      ));
} catch(err) {
     debug( 'Could not access %s (%s)', root, err); 
}
```

**Comment by SBoudrias** [comment]
@yannickadam want to send a PR?

**Comment by SBoudrias** [comment]
Released a new version with this fix.
